[project]
name = "data-sci-practise"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.1.4",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "ruff>=0.9.7",
]
